version: '3'

services:
  # nodejs service for the main app
  node-backend:
    build:
      context: ./backend
      dockerfile: nodejs.Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "9229:9229"
    # Keeps refreshing changes happen inside src dir
    volumes:
      - './backend:/var/www'
    # Environment vars for the App
    env_file:
      - .env
    # Restart the server if it's crashing
    restart: always
    depends_on:
      - postgres
    container_name: 'vr-node-backend'
  # postgres service for db
  postgres:
    build:
      context: ./backend
      dockerfile: postgres.Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    container_name: 'vr-postgres'
  node-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - FORCE_NPM_I=${FORCE_NPM_I}
        - NODE_ENV=${NODE_ENV}
    # Keeps refreshing changes happen inside src dir
    volumes:
      - ./frontend:/var/www
      - ./frontend/docker-etc/node/logs:/root/.pm2/logs
    # Environment vars for the App
    env_file:
      - .env
    # Restart the server if it's crashing
    restart: always
    container_name: 'vr-node-frontend'
  node-cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
      args:
        - FORCE_NPM_I=${FORCE_NPM_I}
        - NODE_ENV=${NODE_ENV}
    # Keeps refreshing changes happen inside src dir
    volumes:
      - ./cms:/var/www
      - ./cms/docker-etc/node/logs:/root/.pm2/logs
    # Environment vars for the App
    env_file:
      - .env
    # Restart the server if it's crashing
    restart: always
    container_name: 'vr-node-cms'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${NODE_ENV}
        - BACKEND_PORT=${BACKEND_PORT}
        - CMS_PORT=${CMS_PORT}
        - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - ${BACKEND_PORT}:8000
      - ${CMS_PORT}:3000
      - ${FRONTEND_PORT}:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    container_name: 'vr-nginx'
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/logs:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    container_name: 'vr-certbot'
    depends_on:
      - nginx
      - node-backend
      - node-cms
      - node-frontend
networks:
  default:
    external:
      name: vr-wedding_network